version: '3'

networks:
  basic_network:
    driver: bridge
    ipam:
      config:
       - subnet: 10.0.88.0/24

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    container_name: elasticsearch
    logging:
      driver: none
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    ports:
      - 9200:9200
    networks:
      - basic_network
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 60s
      timeout: 30s
      retries: 3

  match:
    build: .
    image: imatch
    ports:
    - 8099:80
    command: ["/wait-for-it.sh", "-t", "60", "elasticsearch:9200", "--", "gunicorn", "-b", "0.0.0.0:80", "-w", "4", "server:app"]
    links:
    - elasticsearch
    networks:
      - basic_network
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost/ping || exit 1"]
      interval: 60s
      timeout: 30s
      retries: 3


