name: publish
on:
  push:
    branches: ['production']

jobs:
  build-and-publish-latest:
      runs-on: ubuntu-latest

      steps:
          - uses: actions/checkout@v2 # Checking out the repo
          - name: Build and Publish latest Docker image
            uses: VaultVulp/gp-docker-action
            with:
                github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
                image-name: match # Provide only Docker image name, tag will be automatically set to latest
                dockerfile: Dockerfile
