name: publish
on: [push]
jobs:
publish-match-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ github.token }}
- name: Build the match-docker Docker image
run: |
       docker build . --tag ghcr.io/mmandrille/match:latest
       docker run ghcr.io/mmandrille/match:latest
       docker push ghcr.io/mmandrille/match:latest